# Coolify deployment configuration
version: 1.0.0
build:
  dockerfile: Dockerfile
  context: .
ports:
  - "80:80"
environment:
  - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
  - VITE_SUPABASE_PUBLISHABLE_KEY=${VITE_SUPABASE_PUBLISHABLE_KEY}
healthcheck:
  path: /health
  interval: 30s
  timeout: 10s
  retries: 3

