// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { getConfig } from '@/lib/config';

// Runtime-safe: supports Docker/Coolify via window.__ENV__ (see /public/env.js + docker-entrypoint.sh)
const cfg = getConfig();

// Use placeholders to avoid crashing the UI if env is missing (will still fail calls).
const SUPABASE_URL = cfg.api.supabaseUrl || 'https://placeholder.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = cfg.api.supabaseKey || 'public-anon-key';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});